# Generated by Django 4.1.5 on 2023-02-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lab_id',
            field=models.IntegerField(default=0),
        ),
    ]
