# Generated by Django 4.1.5 on 2023-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0002_service_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_description',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
