# Generated by Django 4.1.5 on 2023-02-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0003_alter_lab_lab_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='new_service',
            new_name='select_service',
        ),
    ]
