# Generated by Django 4.1.5 on 2023-02-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0004_rename_new_service_service_select_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(default=None, max_length=100)),
                ('contact_phone', models.CharField(default=None, max_length=100)),
                ('contact_lab_date', models.DateField()),
                ('contact_enquiry', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
