# Generated by Django 4.1.5 on 2023-02-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0005_contactlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('reviewer_name', models.CharField(default=None, max_length=100)),
                ('reviewer_email', models.CharField(default=None, max_length=100)),
                ('reviewer_description', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
