# Generated by Django 4.1.5 on 2023-02-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0007_review_review_lab_id_alter_review_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklab',
            name='lab_id',
            field=models.IntegerField(default=0),
        ),
    ]
