# Generated by Django 4.1.5 on 2023-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0009_alter_service_select_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='consulting',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='manufacturing',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='otherservice',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='rnd',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='testing',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='whitelab',
        ),
        migrations.RemoveField(
            model_name='service',
            name='select_service',
        ),
        migrations.AddField(
            model_name='lab',
            name='service_list',
            field=models.JSONField(default={'certification': None, 'consulting': None, 'inspection': None, 'manufacturing': None, 'rnd': None, 'testing': None, 'whitelab': None}),
        ),
        migrations.AddField(
            model_name='service',
            name='service_list',
            field=models.JSONField(default={'certification': None, 'consulting': None, 'inspection': None, 'manufacturing': None, 'rnd': None, 'testing': None, 'whitelab': None}),
        ),
    ]
