# Generated by Django 4.1.5 on 2023-02-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0010_remove_lab_certification_remove_lab_consulting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_list',
        ),
        migrations.AddField(
            model_name='service',
            name='select_service',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
