# Generated by Django 4.1.5 on 2023-02-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0011_remove_service_service_list_service_select_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='test_request_form',
        ),
    ]
