# Generated by Django 4.1.5 on 2023-02-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0012_remove_service_service_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklab',
            old_name='connote',
            new_name='sample_tracking_id',
        ),
    ]
