# Generated by Django 4.1.5 on 2023-02-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0016_alter_booklab_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklab',
            name='packaging',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='booklab',
            name='packaging_details',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='booklab',
            name='samples_ready_for_collection',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='booklab',
            name='samples_ready_for_delivery',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='booklab',
            name='special_delivery_instructions',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
