# Generated by Django 4.1.5 on 2023-02-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0018_booklab_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
        migrations.AddField(
            model_name='service',
            name='test_request_form',
            field=models.FileField(blank=True, upload_to='my_file'),
        ),
    ]
