# Generated by Django 4.1.5 on 2023-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0019_service_service_image_service_test_request_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='new_category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='new_service',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
