# Generated by Django 4.1.5 on 2023-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0020_service_new_category_service_new_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklab',
            name='service_status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
