# Generated by Django 4.1.5 on 2023-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0022_alter_lab_lab_image_alter_lab_lab_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_url',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='logo',
            field=models.ImageField(default=None, upload_to='my_file'),
        ),
    ]
