# Generated by Django 4.1.5 on 2023-02-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0023_alter_lab_lab_url_alter_lab_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_image',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='logo',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
    ]
