# Generated by Django 4.1.5 on 2023-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0024_alter_lab_lab_image_alter_lab_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_image', models.FileField(default=None, upload_to='my_file')),
                ('logo', models.FileField(default=None, upload_to='my_file')),
            ],
        ),
    ]
