# Generated by Django 4.1.5 on 2023-02-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0025_labimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labimage',
            name='logo',
        ),
    ]
