# Generated by Django 4.1.5 on 2023-02-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0027_alter_labimage_lab_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labimage',
            name='lab_image',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
    ]
