# Generated by Django 4.1.5 on 2023-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0034_remove_labimage_lab_image_labimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labimage',
            name='images',
        ),
        migrations.AddField(
            model_name='labimage',
            name='lab_image',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
    ]
