# Generated by Django 4.1.5 on 2023-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0035_remove_labimage_images_labimage_lab_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='courier',
            field=models.BooleanField(default=False),
        ),
    ]
