# Generated by Django 4.1.5 on 2023-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0037_imagefile_remove_labimage_lab_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labimage',
            name='lab_image',
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.AddField(
            model_name='labimage',
            name='lab_image',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
    ]
