# Generated by Django 4.1.5 on 2023-02-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0038_remove_labimage_lab_image_delete_imagefile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='lab_image',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='logo',
        ),
    ]
