# Generated by Django 4.1.5 on 2023-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0039_remove_lab_lab_image_remove_lab_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='address2',
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_image',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
        migrations.AddField(
            model_name='labimage',
            name='logo',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
    ]
