# Generated by Django 4.1.5 on 2023-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlab', '0040_remove_lab_address2_lab_lab_image_labimage_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='logo',
            field=models.FileField(default=None, upload_to='my_file'),
        ),
    ]
